name: env
channels:
  - defaults
  - conda-forge
dependencies:
  - appdirs=1.4.3=py37h28b3542_0
  - appnope=0.1.0=py37_0
  - arrow=0.13.1=py37_0
  - asn1crypto=1.3.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - binaryornot=0.4.4=py_1
  - black=19.10b0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cffi=1.14.0=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py37_0
  - cookiecutter=1.6.0=py37_1000
  - cryptography=2.8=py37ha12b0ac_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h90a0687_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=h0a44026_0
  - flake8=3.7.9=py37_0
  - freetype=2.9.1=hb4e5f40_0
  - future=0.18.2=py37_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.63.1=hd977a24_0
  - icu=58.2=h4b95b61_1
  - importlib_metadata=1.5.0=py37_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.12.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.16.0=py37_0
  - jinja2=2.11.1=py_0
  - jinja2-time=0.2.0=py_2
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.3.4=py37_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.1=py37_0
  - jupytext=1.3.0=0
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h9aa3819_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - mypy_extensions=0.4.3=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - ncurses=6.2=h0a44026_0
  - notebook=6.0.3=py37_0
  - numpy=1.17.2=py37h99e6662_0
  - numpy-base=1.17.2=py37h6575580_0
  - openssl=1.1.1d=h1de35cc_4
  - pandas=0.25.1=py37h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.6.1=py_0
  - pathspec=0.7.0=py_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=20.0.2=py37_1
  - poyo=0.5.0=py_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.19=py37_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.5.2=py_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.15.7=py37h1de35cc_0
  - pysocks=1.7.1=py37_0
  - python=3.7.4=h359304d_1
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyzmq=18.1.1=py37h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.6.0=py_1
  - readline=7.0=h1de35cc_5
  - regex=2020.2.20=py37h1de35cc_0
  - requests=2.22.0=py37_1
  - scipy=1.4.1=py37h9fa6033_0
  - seaborn=0.9.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=45.2.0=py37_0
  - simple-salesforce=0.74.2=py_1
  - sip=4.19.8=py37h0a44026_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - statsmodels=0.11.0=py37h1de35cc_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - toml=0.10.0=py37h28b3542_0
  - tornado=6.0.3=py37h1de35cc_3
  - traitlets=4.3.3=py37_0
  - typed-ast=1.4.1=py37h1de35cc_0
  - typing_extensions=3.7.4.1=py37_0
  - urllib3=1.25.8=py37_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.34.2=py37_0
  - whichcraft=0.6.1=py_0
  - widgetsnbextension=3.5.1=py37_0
  - xlsxwriter=1.2.6=py_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - autopep8==1.4.4
    - idna==2.8
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyterthemes==0.20.0
    - lesscpy==0.13.0
    - lxml==4.4.1
    - nb-pdf-template==4.0.0
    - pathlib-mate==0.0.15
    - ply==3.11
    - pycodestyle==2.5.0
    - python-dotenv==0.10.3
    - pyyaml==5.1.2
    - reportforce==0.0.3
    - salesforce-reporting==0.1.2
    - sqlalchemy==1.3.12
    - tabulate==0.8.6
    - uszipcode==0.2.4
prefix: //anaconda3/envs/env
